apiVersion: v1
kind: Service
metadata:
  name: mcpmesh-service
  namespace: mcpmesh
spec:
  selector:
    app: mcpmesh
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP